### ISSUE TITLE
建议录制结束后重新封装为mp4

### ISSUE THREAD

**Issue by aliofwind** [HMBSbige/AutoSplitVideo#1]
由于flv的时间戳问题经常导致较长的flv视频会出现进度条无法使用、跳转等待时间长之类的问题，建议每次录制结束后都直接通过ffmpeg重新封装为mp4，解决后患

**Comment by HMBSbige** [comment]
软件自带转封装功能，每次录制完成后建议自行操作

**Comment by aliofwind** [comment]
就是因为录的直播间多了才需要自动重封装

**Comment by HMBSbige** [comment]
最新的commit，支持检查文件夹根目录的flv，全移到一个文件夹不就行了

**Comment by aliofwind** [comment]
录制的视频文件名只有时间，没有直播间信息，同时录十几个直播间的话把flv都放到一个文件夹里没法分辨

**Comment by HMBSbige** [comment]
那我就改成遍历文件夹内所有flv，这样可以了吧

**Comment by aliofwind** [comment]
那直接加一个结束后自动封装的选项不是更省时间省精力吗

**Comment by HMBSbige** [comment]
然而遍历文件夹内所有flv只要改个参数

结束后自动封装还要写一个异步任务，要是很多直播间同时关，还要加个转封装的队列...

**Comment by HMBSbige** [comment]
结束后自动封装，不是我目前最优先的任务

你可以每次录制完成后自行操作，直接拖文件夹就行了

**Comment by aliofwind** [comment]
视频路径和输出路径选D:\FLV\，子文件夹中flv封装之后的mp4都到了D:\FLV\目录，不在子文件夹里。。。。

**Comment by HMBSbige** [comment]
所以就很烦...

**Comment by aliofwind** [comment]
要不ffmpeg模式直接保存成mp4？

**Comment by HMBSbige** [comment]
也行，但这会增加录制时系统的开销，而且我还没实用过 ffmpeg 模式，不知道网络不行的时候能不能及时重连

**Comment by HMBSbige** [comment]
现在应该可以正确转一个文件夹内的所有 flv 了

**Comment by aliofwind** [comment]
![image](https://user-images.githubusercontent.com/35068322/56577074-a96a7100-65fc-11e9-8fe8-4e98ef05cbf0.png)
![image](https://user-images.githubusercontent.com/35068322/56577076-ac656180-65fc-11e9-8755-a76bf89183c4.png)
这√勾不上啊

**Comment by HMBSbige** [comment]
因为还没写好啊

**Comment by HMBSbige** [comment]
终于写好了
:D

**Comment by aliofwind** [comment]
重新封装的时候ffmpeg的参数有问题，加-copyts会出现mp4时间轴依旧出错，重新封装就是为了重新建立时间戳，不能复制使用flv的时间戳

**Comment by HMBSbige** [comment]
有没有能测试的 flv

**Comment by aliofwind** [comment]
我录的flv都好大，传不上去，晚上看看有没有小一点的

**Comment by aliofwind** [comment]
我传到onedrive了，直接把地址贴这还是先加个QQ？

**Comment by HMBSbige** [comment]
直接贴这吧

**Comment by aliofwind** [comment]
https://aowow-my.sharepoint.com/:v:/g/personal/aliofwind_aowow_onmicrosoft_com/Ec53gc1apC1BpZ-4hoz69DUBXQOdDQeFzww3NP2iL8vqQw?e=zIw0zn

**Comment by HMBSbige** [comment]
我之前是没进度条，不加 -copyts，就会声画不同步

你这是时间轴大于实际的时间还行

我有空修复一下

**Comment by HMBSbige** [comment]
如果有新的 bug，另开 issue 吧

**Comment by zhz1237ok** [comment]
膜拜大佬，找了半天，就你家的录播姬用的最舒服，居然还能修复flv的时间轴，直接变成mp4

**Comment by HMBSbige** [comment]
> 膜拜大佬，找了半天，就你家的录播姬用的最舒服，居然还能修复flv的时间轴，直接变成mp4
> 
> 能悄咪咪告诉我是不是用了ffmpeg吗，怎么软件里没有ffmpeg的，难道封到dll里去了

当然有 ffmpeg 了，目录里不是释放了吗...
