### ISSUE TITLE
不明原因，录制结束后会闪退

### ISSUE THREAD

**Issue by HaDX-MLL** [HMBSbige/AutoSplitVideo#12]
在主播下播后会闪退，开两个以上直播录制的情况下更容易触发。

**Comment by HMBSbige** [comment]
我自己没有这个问题，不知道有没有其他人出现同样的问题

**Comment by HaDX-MLL** [comment]
加了2G内存，再看几天，不确定是不是因为内存小的关系

**Comment by HaDX-MLL** [comment]
依旧是有这个闪退问题，两台机器ATOM D2550 内存4G和I3 8100 内存16G都有这问题

**Comment by HMBSbige** [comment]
如果日志没有显示什么问题我也帮不了你，我这边同时录很多主播都没什么问题

**Comment by HMBSbige** [comment]
2.1.2 版本可能修复了这个 Bug

**Comment by HaDX-MLL** [comment]
新版本使用没问题，没出现闪退的情况了
