### ISSUE TITLE
视频处理-手动剪辑无效

### ISSUE THREAD

**Issue by Billy1105** [HMBSbige/AutoSplitVideo#14]
如标题，在使用视频处理-手动剪辑功能时，设置了开始时刻与持续时间
实际输出的视频只进行了开始时刻的截取，并没有按照设置的持续时间截取最后时刻，而是输出**从开始时刻至原视频末** # #
附加：开始时刻与持续时间输入有问题

**Comment by HMBSbige** [comment]
应该是你输入错了

详细举出自己的例子

**Comment by Billy1105** [comment]
刚刚又检查了很久，发现第一次使用的时候是没有问题的，但再次想修改数字的时候就会出错
例：第一次使用欲设置开始时刻00:00:40.000，持续时间00:06:26.000,在输入时，预设持续时间的01:30:00.000其中130三位数字会随着输入逐渐向右位移，最后1,3分别停在十分秒和千分秒的位置上，不论怎么再输入都会卡住。然后**再次要修改的时候光标的就会错位**，不能正常输入

**Comment by HMBSbige** [comment]
看不懂你在说什么

直接全选退格不就全是0吗，然后再输入...不是很简单的操作吗

**Comment by Billy1105** [comment]
确实全是0但是只要再输入就会变回全部退格前的数字然后之后再怎么操作都动不了

**Comment by HMBSbige** [comment]
要不你录个gif？

先确保全部文件都在，没被删掉

**Comment by Billy1105** [comment]
![GIF](https://user-images.githubusercontent.com/49872483/76340101-fb5fd680-6335-11ea-9446-dd483f12c8d8.gif)

**Comment by HMBSbige** [comment]
不是很懂你要输入什么

**Comment by Billy1105** [comment]
12分34秒,反复输入

**Comment by HMBSbige** [comment]
你详细描述一下步骤？

**Comment by Billy1105** [comment]
电脑重启之后就正常了。。。真奇怪，怎么样都不能复现之前的问题。。。先close算了。。
