### ISSUE TITLE
无法获取Access Token

### ISSUE THREAD

**Issue by xxxxuanran** [HMBSbige/AutoSplitVideo#16]
如题，已经确保账号密码正确。
有尝试过修改密码，也确保没有开启登录验证
APP/网页正常登录，用的是家里的电脑不应该会有问题
也已经重启过路由器重新拨号更换ip了，仍然无法登录
而其他某些B站挂机软件可以正常登录使用，会不会是登录api失效？

**Comment by HMBSbige** [comment]
应该是失效了，有空更新

你可以浏览器登录后自行获取 `Cookie` 里的 `SESSDATA`

**Comment by HMBSbige** [comment]
已临时修复，如果还是不行可以 Reopen 这个 issue

**Comment by HMBSbige** [comment]
又测了下之前的版本又可以了，看来是B站在搞事情
