### ISSUE TITLE
弹幕服务器协议弃用v1启用v2，导致软件不停发送请求

### ISSUE THREAD

**Issue by SekiBetu** [HMBSbige/AutoSplitVideo#18]
![image](https://user-images.githubusercontent.com/38283893/78978845-34fe4a00-7b4d-11ea-84e3-a4de63b9f4ac.png)

复现方法：启动软件即可在日志区观察到

**Comment by Skimige** [comment]
https://github.com/Bililive/BililiveRecorder/commit/36dee0b1aa799222ba486eb1633e2c162188bb3b 上游项目已经更新了新版协议

**Comment by SekiBetu** [comment]
> [Bililive/BililiveRecorder@36dee0b](https://github.com/Bililive/BililiveRecorder/commit/36dee0b1aa799222ba486eb1633e2c162188bb3b) 上游项目已经更新了新版协议

对这个项目印象不是很好，以前第一次用就出BUG，然后我反馈了，他说这不是BUG，后来过了好久据说才修复

**Comment by HMBSbige** [comment]
大家都很忙的，我也是抽出时间更新的

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/78989243-ae099b80-7b65-11ea-9b0a-b2abfbc1f7d3.png)
我没特意说一定要他修，我只是反馈了我鼠标点击这块区域程序就会卡死，他说这不是BUG，本来就这样的，我就感觉，不对，不是这样的，于是估计拖了半年，才修了这个BUG
