### ISSUE TITLE
功能建议：直播通知但是不录制//或者说是选定的直播间自动监视并录制

### ISSUE THREAD

**Issue by zhz1237ok** [HMBSbige/AutoSplitVideo#2]
只有特定选定的直播间会录制，其他的直播间开播的时候只有WIN10通知，因为一般人不会全都录制的，但是又想知道哪个直播间开播了，所以希望增加这个功能

**Comment by HMBSbige** [comment]
要求挺高哦，等着我有空再用 WPF 重写的时候再搞吧

**Comment by zhz1237ok** [comment]
其实就是把现在的关闭录制功能变成只关闭录制，不关闭直播状态检测，功能更加符合关闭录制这个意思

**Comment by HMBSbige** [comment]
[2.0.0](https://github.com/HMBSbige/AutoSplitVideo/releases/tag/2.0.0) 已实现
