### ISSUE TITLE
视频分段里的封装修复是什么功能？

### ISSUE THREAD

**Issue by zhz1237ok** [HMBSbige/AutoSplitVideo#4]
是指切割视频完修复flv的时间轴？不太懂

**Comment by HMBSbige** [comment]
就是修复时间戳，有时候录下来时间戳会有跳变。比普通转封装慢一倍

**Comment by zhz1237ok** [comment]
似乎不需要修复时间轴吧，虽然flv的时间轴拖动反应很慢，但是似乎用ffmpeg换了封装成mp4的时候就好了

还是指在封装为mp4之后还有跳变的那种flv？

**Comment by HMBSbige** [comment]
封装成mp4只是复制时间轴啊，录下来没问题就不用修复啊，不用你就别选呗，有问题再选
