### ISSUE TITLE
录制功能失效了？

### ISSUE THREAD

**Issue by zhz1237ok** [HMBSbige/AutoSplitVideo#6]
一直显示黄字的“启动录制中”，然后没反应，文件夹里也没有出现录制的文件
![image](https://user-images.githubusercontent.com/38283893/71668582-6922db80-2da4-11ea-8502-a77279b32893.png)

任何的直播间都这样

日志文件太简单了，也看不出哪里有问题

[20/1/2 21:08:07] [21013446] [雫るる_Official] 开播：【b限】新年快乐
[20/1/2 21:08:08] [21013446] 正在连接弹幕服务器...
[20/1/2 21:08:09] [21013446] 弹幕服务器连接成功

**Comment by HMBSbige** [comment]
我这可以的，可能你网的问题？

![image](https://user-images.githubusercontent.com/19153265/71668591-7213ad00-2da4-11ea-9dba-eee30448ad65.png)

**Comment by zhz1237ok** [comment]
B站会不会banIP的啊，我发现我用手机流量就能录了，换成光钎就不行了

**Comment by HMBSbige** [comment]
可能的，你是不是之前用我老版本的了...

**Comment by zhz1237ok** [comment]
没，用的这里最新的版本，我查了下，本次最后一次成功录制是12月24日，从24日到现在，我的网络环境也没变化过，但是录制不了了，很奇怪

**Comment by HMBSbige** [comment]
正常的日志应该想这样的
![image](https://user-images.githubusercontent.com/19153265/71670868-4f859200-2dac-11ea-9dcd-95238501acb5.png)
如果你没有`连接直播服务器`，浏览器不登录的情况下看看能不能访问
https://api.live.bilibili.com/room/v1/Room/playUrl?cid=21013446&quality=4&platform=web

房间号可以换成在直播的

**Comment by zhz1237ok** [comment]
{"code":19001012,"message":"调用bvc-play-url-one出错","ttl":1,"data":{"current_quality":0,"accept_quality":null,"current_qn":0}}

**Comment by zhz1237ok** [comment]
登录情况下访问确实可以，不登录就上面这个调用出错

**Comment by HMBSbige** [comment]
可能B站又在搞什么限制，过几天把登录做了

**Comment by zhz1237ok** [comment]
cookies读取也行www，登录估计做起来很麻烦

**Comment by HMBSbige** [comment]
之前做过，B站应该不会改

本来是用来做录制付费直播的...

**Comment by HMBSbige** [comment]
可以试试最新的 [2.1.0](https://github.com/HMBSbige/AutoSplitVideo/releases/tag/2.1.0)，没有用的话可以 Reopen 这个 issue

**Comment by zhz1237ok** [comment]
> 可以试试最新的 [2.1.0](https://github.com/HMBSbige/AutoSplitVideo/releases/tag/2.1.0)，没有用的话可以 Reopen 这个 issue

嗯，登陆了账号之后就能录制了，完美
