### ISSUE TITLE
建议开启软件时读取json的配置

### ISSUE THREAD

**Issue by zhz1237ok** [HMBSbige/AutoSplitVideo#7]
刚才调试的时候以防万一备份了一个json配置文件，然后解压了这个新版本，然后发现，新版本每次打开不会读取json里的配置，只会在关闭软件时覆盖保存json

那意味着，每次升级软件，都只能重新添加房间号？

**Comment by HMBSbige** [comment]
只要改变的配置就能保存啊

**Comment by zhz1237ok** [comment]
![image](https://user-images.githubusercontent.com/38283893/71674998-bfe5e080-2db7-11ea-8cb6-80a75438d962.png)
这是关闭软件状态下我修改好了json文件
然后打开软件后
![image](https://user-images.githubusercontent.com/38283893/71675016-cf652980-2db7-11ea-9dd9-965913d246be.png)
如图，被清空了，然后此时json没有发生变化，但是我关闭软件后
打开json看了一眼变成这样了
![image](https://user-images.githubusercontent.com/38283893/71675074-f58ac980-2db7-11ea-8c53-6dac2ac97c84.png)

说明打开软件的时候没有读取json配置，只在关闭软件的时候用新生成的json覆盖了旧的

**Comment by zhz1237ok** [comment]
我的意思是，我手上有一个json配置文件，然后下载了新版本的软件，解压到了一个新的文件夹，并把json放到了新的文件夹，直接开启软件，是无法读取房间和软件里的设置的

**Comment by HMBSbige** [comment]
可以的，不知道你什么问题

你确定json格式写对了吗

**Comment by zhz1237ok** [comment]
{
  "RecordDirectory": "V:\\annie\\VTB",
  "Rooms": [
    {
      "RoomId": 21013446,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": true,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 12235923,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 14917277,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 13946381,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 21130785,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 14327465,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 21107534,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 21320551,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 8725120,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 21545232,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 15152878,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 628674,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": true,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 5064,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": true,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 14052636,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 21656036,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,
      "IsMonitor": false,
      "IsNotify": true,
      "LogTitle": true
    },
    {
      "RoomId": 21584153,
      "TimingDanmakuRetry": 2000,
      "TimingCheckInterval": 300,
      "TimingStreamRetry": 6000,
      "TimingStreamConnect": 3000,

**Comment by zhz1237ok** [comment]
草，我用微软的sticky notes 原来有字数限制，后面一半都没存进去，丢人了
